Update index.html
troubleshooting 
error: results page did not appear when Results button was clicked
edit: added missing end bracket to results() function